### PR TITLE
Remove activesupport version for Rails 6 compatibility

### PR DESCRIPTION
**Pull request by aaronchi**
Required for rails 6 upgrade

### CODE REVIEW

**Comment by ryanswood** [comment]
We unfortunately have a dependency on this gem via [Aptible-Api](https://github.com/aptible/aptible-api-ruby) and are unable to upgrade to Rails 6. The author of the feature that introduced the dependency found it much easier to use the gem to asynchronously initiate scaling and to get a status of an operation. AFAIK, the CLI is not capable of retrieving an operation's status.

Is Aptible willing to consider updating this to remove ActiveSupport or increase its version range? Would it help if I made the changes?

**Comment by ryanswood** [comment]
@almathew AbleHealth uses https://github.com/aptible/aptible-api-ruby which depends on this gem. It is used to asynchronously autoscale Aptible resources and asynchronously check an operation's status. The last I checked the CLI doesn't have the functionality to check an operation's status. I say this because in the back of my mind there was guidance from Aptble to not use the API gem should not be used.

We are now looking to upgrade to Rails 6 which is blocked by the ActiveSupport dependency of this gem. Is Aptible willing to consider updating this gem? What are the options? (remove version, increase version constraint, see if AS is really needed?) How can I help?

**Comment by almathew** [comment]
@ryanswood I'll take a look at what our options are and update you sometime early next week

**Comment by ryanswood** [comment]
@almathew How is the change looking? I am curious if there is a timeline even if it is far out. There is no particular pressure on my end other than seeing the project to unblock an upgrade to Rails 6 to completion. Appreciate the effort.

**Comment by ryanswood** [comment]
@almathew Is there an update?

**Pull request closed without merging**
