### PR TITLE
Remove special type field from adapter

### PR DESCRIPTION
**Pull request by blakepettersson**
Remove special `type` field from adapter; use `_type` if there is a need to (de)serialize to a specific type.

cc @fancyremarker @sandersonet

### CODE REVIEW

**Comment by fancyremarker** [comment]
I'm :+1: on this, but I think we also need to implement aptible/auth.aptible.com#61 to go along with it.

**Comment by blakepettersson** [comment]
Is this something that only needs to be implemented for the views in auth.aptible.com?

**Comment by fancyremarker** [comment]
@blakepettersson: views and a `_type` method in ApplicationDecorator, yes (I think)

**Comment by blakepettersson** [comment]
As I thought, just checking. There's a PR ready in auth.aptible.com now.

**Pull request merged**
