### PR TITLE
Redo of Remove activesupport version for Rails 6 compatibility

### PR DESCRIPTION
**Pull request by almathew**
See: https://github.com/aptible/aptible-resource/pull/43

I aggressively cut down the Ruby versions we're testing (and added at least one that we should be testing). I think I can cut the list even further, I just need to poke around and see.

Some of my rubocop choices could be debatable, but I err'd on the side of not changing anything that could be a functional change right now. 

I still have a bit of testing I want to do downstream (namely with api/sweetness, since that's the source of our heaviest usage), but I _think_ this version should work.

### CODE REVIEW

**Review by fancyremarker — APPROVED** [review]
Works for me — thanks!

**Comment by almathew** [comment]
fyi @ryanswood

**Comment by ryanswood** [comment]
@almathew Thanks for the change. I think all that is needed at this point is to create a release of this gem that is a compatible version with https://github.com/aptible/aptible-api-ruby/blob/master/aptible-api.gemspec#L24.

**Comment by almathew** [comment]
@ryanswood sorry for another long delay, but the new version is released

**Pull request merged**
